### PR TITLE
Fix CONTENTBOX-658

### PR DESCRIPTION
**Pull request by Tropicalista**
Assign a default value to cache if none provided

### CODE REVIEW

**Comment by lmajano** [comment]
merged manually, thanks for you awesomeness!

**Comment by Tropicalista** [comment]
Luis, you should also remove 

    "cb_site_settings_cache"				= "Template",

from installerservice.cfc, otherwise this setting is duplicated in the db and throws an error.

**Comment by lmajano** [comment]
Hmm good point. I guess the issue is that the installer should set it. The other one was a backup. I need to revise this. 

Luis Majano
CEO
Ortus Solutions, Corp
www.ortussolutions.com
P/F: 1-888-557-8057




On Mon, Jan 25, 2016 at 1:30 PM -0800, "Tropicalista" <notifications@github.com> wrote:












Luis, you should also remove 

"cb_site_settings_cache"                = "Template",




from installerservice.cfc, otherwise this setting is duplicated in the db and throws an error.

**Comment by Tropicalista** [comment]
if intereptor can run in order, I would first run the installer and then the ratelimiter, to aoid the cretion of the setting.

Otherwise in installer.cfc I would check if caching setting exists, if no I will add.

Or also better, simply remove the creation of the setting from setting service and if not present in database, read from a default cache value

**Pull request closed without merging**
