### PR TITLE
Added option for users to use reCAPTCHA for comment forms

### PR DESCRIPTION
**Pull request by skeltonm**

### CODE REVIEW

**Comment by GunnarLieb** [comment]
Do know if you have seen that I wrote a module for Contentbox an reCaptcha https://github.com/akitogo/cbReCaptcha

I think it's good to have the option build in for another captcha but I would suggest to implement it in a slightly different way. I'm suggesting make each captcha a module an implement in the core just interfaces.

What do you think?

**Comment by skeltonm** [comment]
@GunnarLieb
First of all, thank you for sharing your module with me, I was not aware that it existed.

Second, regarding your suggestion about modularizing the captcha modules, are you suggesting to extract both the reCaptcha implementation AND the existing captcha implementation out into their own separate modules?  Or are you suggesting to leave the captcha implementation alone and only extract the reCaptcha implementation out to a module?

**Comment by GunnarLieb** [comment]
@skeltonm 

> are you suggesting to extract both the reCaptcha implementation AND the existing captcha implementation out into their own separate modules?

Yes, this makes the most sense for me, what do you think?

**Comment by skeltonm** [comment]
@GunnarLieb Yes, I agree.  Regarding the implementation, would you implement it using interceptors like in your module or would you implement it more like it currently is?

**Comment by GunnarLieb** [comment]
@skeltonm Using an interceptor reduces dependencies, so I would prefer this. What's your preference?

**Comment by skeltonm** [comment]
@GunnarLieb I agree.

**Comment by skeltonm** [comment]
@GunnarLieb I am thinking it would be best to leave the settings handling as I have it in this PR.  Your thoughts on that?  Would you move it to modules instead?

**Comment by GunnarLieb** [comment]
@skeltonm if you include captcha specific settings in core files, you always have to extend core if you want to add other captcha modules. I would prefer to implement it in a more modular way ( this where coldbox and contentbox are heading)

**Comment by skeltonm** [comment]
@GunnarLieb Then how would you handle changing captcha settings?

**Comment by GunnarLieb** [comment]
@skeltonm you mean cb_comments_captcha_type? That should stay, we could say setting contains name of module?

**Comment by skeltonm** [comment]
@GunnarLieb No, I was referring to the reCaptcha settings (public and secret key).

**Comment by GunnarLieb** [comment]
@skeltonm I think this should be set in each module, could be that a new captcha service needs other settings

**Comment by skeltonm** [comment]
@GunnarLieb Then where would you expose those module settings in the admin?  Having the settings in the module would be somewhat non-intuitive for users because they would change the captcha type in the comments settings section but then they would have to go to the module to set the specific module settings.  That seems like a difficult path to follow.

Also, when discussing captcha types, is allowing for captcha types other than coldFusion or reCaptcha really that important?  It would seem to me that those other types (even coldFusion to be honest) are being phased out with reCaptcha being the main type used.  In that respect, having it built more into the core might make sense.

**Comment by GunnarLieb** [comment]
@skeltonm For the settings we have a few options, either we place it as a sub menu via menuservice in settings otherwiese we could generate an interception point in settings.

Since it's a one time setting I would place it as a submenu.

If we are talking about captcha types, I agree, but for me it's more a general approach how you design the software. Maybe you should get some feedback from @lmajano or @gpickin

**Comment by lmajano** [comment]
I think you guys are in the right track.  I say let's decouple captcha entirely from the core. Meaning let's just make sure we can create captcha modules easily.  This way we don't have to include captcha natively into ContentBox.

This would involve the following:

1) Remove native captcha support in ContentBox and moved as custom module

The module would then need to do the following:

1) Listen to `cbui_postCommentForm` or `cbui_preCommentForm` to render out the captcha
2) Listen to `cbui_preCommentPost` for the commit of a comment form.  This receives the following arguments:

* `commentErrors : array`
* `content : object`
* `contentType : string`

If there are errors, you need to append your message to the `commentErrors` array

3) It would be the job of the module to register a settings page for itself.

**Comment by GunnarLieb** [comment]
@lmajano @skeltonm suggested module stuff is implemented in https://github.com/akitogo/cbReCaptcha/blob/master/interceptors/reCaptcha.cfc so it could be reused for reimplementing the cf captcha.

**Comment by GunnarLieb** [comment]
Here is as well a little overview http://www.akitogo.com/blog/implementing-recaptcha-in-contentbox-cms-3x

**Comment by skeltonm** [comment]
@GunnarLieb, @lmajano I am closing this PR and will open a new PR with the updates that have been suggested.

**Pull request closed without merging**
