### PR TITLE
CONTENTBOX-869 Fix

### PR DESCRIPTION
**Pull request by Tropicalista**

### CODE REVIEW

**Comment by lmajano** [comment]
@gpickin thoughts on this pull request?

**Comment by gpickin** [comment]
Having it use a preference is probably a good move, but where are we adjusting the call to read the setting?

**Comment by Tropicalista** [comment]
At the moment every time I toggle the sidebar status the preference is saved in database. 
On the pages/entries editor the preference is not respected, because it always sets the sidebar to mini. 

We have a setting in user management "Collapsed Left Navbar" that should be used to have the sidebar always toggled off on editors pages. The status toggle should be stored in localstorage in my opinion and overridden by "Collapsed Left Navbar" only on editors.

**Comment by lmajano** [comment]
Closing this as it took to long for us to decide on this. Please resubmit when revised

**Pull request closed without merging**
