### PR TITLE
Fix CONTENTBOX-635

### PR DESCRIPTION
**Pull request by Tropicalista**
Not sure if it's the best solution, however this seems to work.

### CODE REVIEW

**Comment by Tropicalista** [comment]
After some other tests, I'm sure that data passed to view is ok. The problem is due to some http header that is inflated in the cached view. If you add

    		event.renderData( data=data.content, contentType=data.contentType, isBinary=data.isBinary );

instead of 
    
    return data.content

the problem is solved and probably is the best soultion, so we can have also pdf cached.

**Comment by Tropicalista** [comment]
I think this is probably due to the fact that around handler is not passing correct http header. Not sure if this is a coldbox bug.

**Comment by Tropicalista** [comment]
This should be closed in favor of this pr: https://github.com/Ortus-Solutions/ContentBox/pull/170

**Comment by lmajano** [comment]
thanks

**Pull request closed without merging**
