### PR TITLE
File browser regressions gp

### PR DESCRIPTION
**Pull request by gpickin**
Fixed regressions introduced by merging @Tropicalista filebrowser changes in.
Can you look through these @Tropicalista and make sure they don't clash with anything you did.

Good work on the file browser, really excited to have all of these changes in place.

### CODE REVIEW

**Comment by gpickin** [comment]
@lmajano please review as well.

**Comment by gpickin** [comment]
Looks like there are issues with this.
I'll keep working on it tonight, to resolve them :(

**Comment by gpickin** [comment]
image

**Comment by gpickin** [comment]
Ok, installed bower again, and that fixed that error.
Since a lot of the context stuff changed, all of the issues we had with context menus needs to be fixed again.
I can't just copy the old code over though, because its a new context menu.

This pull request has the added context menu code.
https://github.com/Ortus-Solutions/ContentBox/pull/281

I cannot find the pull request for that method right now. 
If you look at your cbFileBrowser2 pull, its removed with that merge.

**Comment by Tropicalista** [comment]
@gpickin can you tell me what other errors have you found? The context menu seems to work properly.

**Comment by gpickin** [comment]
The issue most people had, was if you right click on some, that wasn't selected, the context wouldn't show, or if it did, it would show for the selected item.
I updated the older code to select first, so the right click would work.

A lot of the other changes in here fix the selection sizing and highlighting colors with css... so the objects matched the bordered object.

I'm pushing some more changes here shortly, we'll see where I get to.

**Comment by Tropicalista** [comment]
The right click was already fixed. 

About the footer links, you are right, they are missing, however I made very little change to home/index.cfm you can rebase it and then I will do another pull request. I simply made some change to button bar and upload bar. 

Sorry for this

**Comment by gpickin** [comment]
We'll get it worked out. 
This pull request tries to refix the issues.

Do you see anything in these changes that would cause any issues with your code?
I'm troubleshooting it now.

**Comment by Tropicalista** [comment]
Seems ok

**Comment by gpickin** [comment]
OMG - Chrome Dev Tools breaks the Context menus, I think i had it fixed, but having dev tools opened meant I couldn't see it. Driving me crazy.
I think this fix should resolve the context issues.
Pushing code in a minute.

Only 1 outstanding issue I think - Pathing with rewrites.

**Comment by gpickin** [comment]
I'm going to merge it, do a fresh install, and test my changes.
I think the dev tools were causing most of the headaches.

Fingers crossed.

**Comment by gpickin** [comment]
Luis fixed the pathing issues.
We'll all good now.

Glad to have this included. 
Now onto the next major updates.
Thanks everyone

**Pull request merged**
