### PR TITLE
Fix CONTENTBOX-480

### PR DESCRIPTION
**Pull request by Tropicalista**
Useful to add a related image to post

### CODE REVIEW

**Comment by Tropicalista** [comment]
A good idea would be to add an interceptor like this one: https://github.com/Computer-Know-how/cbmodule-photogallery/blob/master/PhotoGallery/interceptors/FileBrowser.cfc

that resize all featured image accordingly to settings, generates also thumbail to display in sidebar or index page.

**Comment by lmajano** [comment]
This is fantastic. I am merging your approach with a module we had built before. Will commit soon so you can review it for me

**Comment by Tropicalista** [comment]
Great, let me know when it's ready. Thanks

**Comment by lmajano** [comment]
Ok, it is ready and merged into development now for testing.

**Comment by lmajano** [comment]
Let me know when you get a chance to test @Tropicalista @gpickin

**Comment by Tropicalista** [comment]
Hi Luis,

the clear button should be displayed each time the hidden form is not empty and not when the model property is empty. For example if I want add an image, select one but then change my mind and not want display it anymore, I cannot remove from the form.

Also if I choose an image and then I prefer to change it and choose another one, the preview is blank.

**Comment by Tropicalista** [comment]
You are also embedding bootstrap and other css two times, this makes the modal show ugly.

**Comment by lmajano** [comment]
hmm, I htink I introduced another bug due to another issue

**Comment by Tropicalista** [comment]
Removing bootstrap css solve this problem. Bootstrap and jquery should be integrated only when filebrowser is loaded by ckeditor...

**Pull request closed without merging**
