### PR TITLE
Remove Captcha from ContentBox core

### PR DESCRIPTION
**Pull request by skeltonm**

### CODE REVIEW

**Comment by skeltonm** [comment]
This PR is meant to remove captcha from the ContentBox core and improve the comment form widget so users can add their own captcha modules.  I have created a captcha module based on the ColdFusion captcha previously used in ContentBox.  It can be viewed on [ForgeBox](https://www.forgebox.io/view/cbCaptcha) or [GitHub](https://github.com/skeltonm/cbCaptcha).

**Comment by skeltonm** [comment]
I have also made a PR to the cbReCaptcha module [here](https://github.com/akitogo/cbReCaptcha/pull/1).  @GunnarLieb if and when this pull request for ContentBox is merged, then the PR to the cbReCaptcha module should be merged so it will work with the updates in this PR.

**Comment by GunnarLieb** [comment]
@skeltonm cbRecaptcha is updated und published to Forgebox

**Comment by lmajano** [comment]
Thanks guys. So can I safely incorporate this. Do we have alternatives now?

**Comment by skeltonm** [comment]
Luis,

Yes, @GunnarLieb updated his module which is the reCAPTCHA implementation and I created a module from what existed in ContentBox already.  Links below:

[reCAPTCHA module](https://www.forgebox.io/view/cbReCaptcha)

[ColdFusion Captcha module](https://www.forgebox.io/view/cbCaptcha)

**Comment by lmajano** [comment]
@skeltonm will have to merge this manually, too many changes since I merged the two factor auth. Will close and link, once merged.

**Comment by lmajano** [comment]
Done!

**Pull request closed without merging**
