### PR TITLE
Removed trailing spaces from all ContentBox files

### PR DESCRIPTION
**Pull request by skeltonm**
Not sure if this is a pull request you would like to use, but I thought it would be good to clean up the trailing spaces in all of the ContentBox files.  Do with it what you will.

### CODE REVIEW

**Comment by lmajano** [comment]
Unfortunately it claims conflicts?

**Comment by lmajano** [comment]
oops, closed it by accident

**Comment by skeltonm** [comment]
I will try to reverse the commit and retry the commit, I have the removal of the trailing spaces scripted so it won't take me long.  I will try to get to that later today.

**Comment by skeltonm** [comment]
Luis,
I am going to close this and reopen it with the updates.

**Pull request closed without merging**
