### PR TITLE
Removed trailing spaces from all ContentBox files

### PR DESCRIPTION
**Pull request by skeltonm**
Luis,

I have updated my repo to the latest and rerun my remove trailing spaces script.

### CODE REVIEW

**Comment by lmajano** [comment]
@skeltonm I think this will totally pollute the updaters, so not sure what to do, thinking about it.

**Comment by skeltonm** [comment]
@lmajano I made a Gist with the Python script I made if you would like to use it.  Here is the link: https://gist.github.com/skeltonm/994bfd084070bf65c0b1a13460da2e4b

**Comment by lmajano** [comment]
I can offer a $25 amazon card if you make that a CommandBox command! @bdw429s

**Comment by skeltonm** [comment]
Luis,

I'll work on that.  That is a great idea to put it in CommandBox!

**Comment by skeltonm** [comment]
Luis,

I opened a PR to CommandBox to add the remove trailing spaces command.  Regarding this PR, if it is not going to work then go ahead and close it.

**Pull request closed without merging**
