### PR TITLE
Filebrowser UI improvement

### PR DESCRIPTION
**Pull request by Tropicalista**
Update UI to be more in keeping with rest of admin

### CODE REVIEW

**Comment by lmajano** [comment]
@Tropicalista I merged this manually do to several additions and updates. It looks awesome now thanks to you :)

**Comment by lmajano** [comment]
Check it out: https://github.com/Ortus-Solutions/ContentBox/commit/673b7a2031ccaedc37e220dab87f134333870da1

**Comment by Tropicalista** [comment]
There are two different id one named FileBrowser and another filebrowser. I followed previous naming, that does not generate confusion because the latter were not used in js, However I think it's better reorganize the naming of the div and modify the js accordingly. I have tested and my channges are working great. Better naming is due.

**Comment by lmajano** [comment]
I have udpated it, can you verify please

**Comment by Tropicalista** [comment]
Yes, it works great!

**Pull request closed without merging**
