### PR TITLE
Add index.cfm into the ModuleConfig for contentbox to fix installer w…

### PR DESCRIPTION
**Pull request by gpickin**
…ith no rewrites

### CODE REVIEW

**Comment by gpickin** [comment]
https://ortussolutions.atlassian.net/browse/CONTENTBOX-815

**Comment by lmajano** [comment]
Merged manually in order to avoid two place edits.

**Comment by bdw429s** [comment]
@lmajano Did you see my comment on the ticket?  I think we should improve this to actually look at the base URL to see if it has index.cfm.  Right now, the solution is not ideal because it 
1) Forces people to update two places to change 
2) Forces people to update core ContentBox code that will be overwritten on the next upgrade.

**Comment by lmajano** [comment]
I did that.

**Comment by bdw429s** [comment]
@lmajano Interesting.  Andrew Davis posted the next day on Slack that this change had broken his app by forcing the index.cfm again.  I wonder if the code didn't work.  @gpickin Can you test Luis' version of the fix?

**Comment by lmajano** [comment]
It basicallydetects he index.cfm in the ses base URL. If there then it appends

**Pull request closed without merging**
