### PR TITLE
refactor: remove unneeded trailing whitespace

### PR DESCRIPTION
**Pull request by jbampton**

### CODE REVIEW

**Comment by lmajano** [comment]
@jbampton is there a purpose behind this PR? The diff her in github is not so great at whitespace diff.

**Comment by jbampton** [comment]
Most other languages hate trailing whitespace and there are lots of reasons why you should strip trailing whitespace from your files.
Some of those reasons are:

- it doesn't need to be there
- it makes your files larger
- larger files make for bigger downloads (slower user experience, using up more CPU cycles etc)
- Code should be standardardized and not have extra bits in some places

Hey @lmajano you can hide the whitespace changes here on the GitHub website on the `Files Changed` tab.

Screen Shot 2021-02-15 at 1 39 20 am

**Comment by jclausen** [comment]
Looks like a good little cleanup of some extra whitespace.  One thing to note @jbampton is that, since CFML is a compiled language, the extra whitespace doesn't really matter, as the bytecode compilation strips and optimizes all of that anyway. 

It looks like a lot of the conversions are coverting from CRLF to LF, which is fine.  The only downside of that might be for a windows user who opens up one of the files in Notepad, which only knows CRLF.  Nowadays, though, all decent text editors and IDE's know how to render both.

**Comment by bdw429s** [comment]
@jclausen Actually, this setting
https://github.com/Ortus-Solutions/ContentBox/blob/development/.gitattributes#L2
will ensure that line endings are converted to CRLF for Windows users when they clone the repo in their Git client.  They will be converted back to LF in the repo on commit.

**Comment by jbampton** [comment]
Hey @jclausen that `Notepad` issue you mentioned normally doesn't happen if you install Git properly.

You choose the correct setting and it will never happen:

Screen Shot 2021-02-22 at 12 34 42 pm

**Comment by jclausen** [comment]
> Hey @jclausen that `Notepad` issue you mentioned normally doesn't happen if you install Git properly.
> 

You’re absolutely correct, providing that Git is or can be installed.  I work with clients who run air-gapped servers where this is not possible.

**Comment by lmajano** [comment]
will need to close as too many changes have passed

**Pull request closed without merging**
