### PR TITLE
Fix CONTENTBOX-492

### PR DESCRIPTION
**Pull request by Tropicalista**
Some ui improvements

### CODE REVIEW

**Comment by lmajano** [comment]
WOW!! Sooooo good!

**Comment by lmajano** [comment]
@Tropicalista I merged, but now that I have tested, I have noticed that the builk actions z-index is out of wack.  Can you verify this please.

**Comment by Tropicalista** [comment]
Which z-index?

**Comment by Tropicalista** [comment]
Ah ok, you're right, I will fix and make another pr

**Pull request merged**
