### PR TITLE
Improvement on filebrowser

### PR DESCRIPTION
**Pull request by Tropicalista**
Added a more powerful and also simple context menu, preview show in modal, better form disposition

### CODE REVIEW

**Comment by lmajano** [comment]
@Tropicalista I almost cried when I saw this!! WOW!! 
Few comments though:

- Cropping does not work on the selected image (Chrome). Meaning it does not crop the selected cuadrant but always crops from the top left corner. See attached images
- Save Button does nothing, no errors on console or anything. @
screen shot 2016-07-07 at 2 56 05 pm
screen shot 2016-07-07 at 2 56 10 pm

**Comment by Tropicalista** [comment]
I have tried on chrome with the default image embedded in contentbox and also with some jpeg. However I will investigate further...

**Comment by lmajano** [comment]
Any updates on this @Tropicalista , I want to include this in the release

**Comment by Tropicalista** [comment]
Hi Luis, I've just fixed some error and added better UI. 

However there are some fix needed. For example a way to enable/disable crop feature if resizing and viceversa.

Also I'm not sure about this part:

`		if ( len(rc.imgLoc) ){

		    // read the image and create a ColdFusion image object --->
		    var sourceImage = ImageNew( imgLoc );

		    // crop the image using the supplied coords from the url request 
		    ImageResize(	sourceImage,
	                        rc.width,
	                        rc.height);

		    cfimage (
		        action = "writeToBrowser",
		        source = sourceImage
		    );

		    abort;

		}`

Is there a better way to render image to browser? 

Also I want to add a flag to check if we wnat overwrite old image or create a new one.

I have tested saving with some images and seems to work.

**Comment by Tropicalista** [comment]
I think it's almost finished. 

Probably a little more improvement should be done on file upload

**Comment by lmajano** [comment]
Great I will revise next week and post my comments. Off the bat some suggestions we had was to allow for a save and override original and another for save as new file. Is this possible? I think this has great potential to become our image tools in the future.

**Comment by Tropicalista** [comment]
Yes, I was already working on this.

**Comment by lmajano** [comment]
Hi @Tropicalista now that 3.0.0 is out, can we revise this again please?

**Comment by bdw429s** [comment]
@lmajano @Tropicalista What's the status on this pull?  It's been around for a while.  If it's stable as is, can we merge it in and improve it incrementally in later pulls?  It's been sitting around for too long.

**Comment by lmajano** [comment]
@Tropicalista can we pick up this pull request again so we can merge into 3.1.  If I remember it had a few issues.  Can you verify?

**Comment by Tropicalista** [comment]
Hi Luis, I will check asap.

**Comment by lmajano** [comment]
Welcome back @Tropicalista  we have certainly missed you

**Comment by lmajano** [comment]
Any feedback @Tropicalista

**Comment by Tropicalista** [comment]
Hi Luis, I was busy in those days. However I've checked and seems that I should fix some problem with png and png transparent background. I will try to make a pr in next days.

**Comment by lmajano** [comment]
Thank you so much @Tropicalista I will test as well.

**Comment by gpickin** [comment]
Finally taking some time to test it out.
Looks like the view is missing?

missinginfo

**Comment by gpickin** [comment]
This looks really solid. I like the functionality.. great work.

There are a few things I would like to add, please take them as constructive add-ons.
Most important first.

- Save As Option - I think having this overwrite the original is kind of dangerous. Maybe introduce a naming convention where you rename the original as xxx_orig.png or something like that.
- Duplicate - I think if you are going to overwrite, having the ability to copy, overwrite etc would be useful.

The next set of features are UI updates and additional functionality - Mimicking my common use cases in photoshop / fireworks.

- I'd like a option for manually updating the crop / canvas size numbers in the resize x y left right fields. Maybe have an option to unlock them, so they're locked by default, but it would be nice to be able to manually set those values. 
- I'd like an option for center horizontally or vertically for the size too. So maybe I'd make it 300 x 200, but i would want to center it. 
- For scale, maybe have a slider from 100% in the middle, and then up and down, with fields for the percentage
- For scale, maybe have a constraint proportions lock, so you could squish an image if you want.
- It might even be nice to give a proportion ratio, and calculate the best crop for it. A lot of the time, I have 300x225 thumbs, so i want me large formats to match. So usually i get the smallest ratio, and then divide... so i might have a 1000 x 500 pixel wide image, but if i ask for it in 300x225 it would give me a 667 x 500 crop... which of course i could move up and down to capture it best. I do this all the time, i hate having to grab a calculator, or worse do math lol.

I love what you have done, but these are some of the features I would love to see in it.

**Comment by gpickin** [comment]
In addition to the proportion ratio, Esme suggested preset ratios, 3:2, square etc... just like instagram and other photo tools.

It might be nice to have transformation tools, rotate 90, 180 270, etc.

**Comment by gpickin** [comment]
When editing the image in a reduced size window, the image width was not restricted so the images overflows the area horizontally, and lays under the controls.
Looks like the image scales based on the maximum height, but doesn't take width into consideration.

**Comment by gpickin** [comment]
When trying to add an image from content, like a page, when you right click, the EDIT IMAGE and INFO do not work. I see no errors in dev tools,

It must be the fact that the media manage is in a modal, and its trying to load another modal.
So this needs to be fixed, or disabled.
I think its great to have it working here, but maybe we can disable for 3.1 and then keep working on it.

@lmajano thoughts?

**Comment by lmajano** [comment]
I think that this is a good start.  For the next iteration I think we should be forward thinking and move it to Vue.js completely and start building it out.  If not, we will never get rid of our old jquery approach.

**Comment by lmajano** [comment]
@Tropicalista the info view is missing?

**Comment by lmajano** [comment]
Close in favor of https://github.com/Ortus-Solutions/ContentBox/pull/312

**Pull request closed without merging**
