### PR TITLE
Filebrowser2

### PR DESCRIPTION
**Pull request by Tropicalista**
I've added 

- a better context menu

- bootbox prompt instead of browser one

- multiselect (this should be used probably only for removing multiple items?)

- select file for upload in sync with UI

- crop/resize/rotate/flip image (should be tested on big image )

- added overwrite or save as

### CODE REVIEW

**Comment by lmajano** [comment]
This is great, starting to evaluate it. Should I ignore the other pull requests on filebrowser?

**Comment by lmajano** [comment]
I have tested this and found the following issues:

1. Edit/Info should only show up for images and not for any other types of files
image

2. When editing a large image the image is cut out, it does not show all of it.
image

3. Files must be url encoded to deal with files with spaces or odd characters. Upload something called ScreenShot (1).jpg
image

image

4. Multi-select is not working. How do I activate this?

5. Date formatting lost on status bar
image

6. Cropping does not do constraints. It would be great to have the ability to lock the image constraints when scaling.  Something that can be toggled on/off, so either I can scale with constraints or a-la-carte.  Also, weird characters come up once I put in a numeric value in the scale box:
image

7. The save as should be pre-filled with the name of the original file so typing is easier.

**Comment by lmajano** [comment]
Forgot 1 more.

When you do manual upload, the file uploads, but there is no response that it uploaded. It should refresh the panel and close the upload

image

**Comment by Tropicalista** [comment]
Hi Luis, thanks for your feedback. Honestly doing this is more complicated than I expected. However I've made some changes:

1. Info now shows for image and files/folders
2. I've tested very big images (3000 x 2000) and seems to work. What browser do you use? I've checked chrome and firefox
3. Files are now urlencoded
4. Multi select works clicking ctrl key (however I'm not sure this would be useful because the oncly action is delete,)
5. Date formatting was same on old filebrowser, however I could change. What format do you want?
6. The error of strange characters is solved. I'm not sure what do you mean by doing constraints. If the image is not scaled proportionally, it will generate really ugly images if user insert unconsistent value. Can you expand?
7. Save as is empty because can be confusing, however I can fill it with the default name if you prefer.
8. Upload now is fixed

However I think this should be huge tested on real site to be sure there is no errors. As it is right now seems a good starting point.

**Comment by Tropicalista** [comment]
Also, you can  ignore the other pull requests on filebrowser

**Comment by lmajano** [comment]
@Tropicalista great work man!!

> Honestly doing this is more complicated than I expected.
LOL, Welcome to my world!!!

Few more things and we are ready to merge:

1) Info Prettier
Can we make the info not be a dump but maybe an info table? It seems too raw!

2) Can we put the URL in a textarea or something so it can be easily copied? Also, can you remove the extra `/` in the URL.
image

3)Uploading works but when it is finished the image never resets and the console never refreshes:
image

4) Flushed buttons.  Can we make these control bottons be the same size, maybe use the block class
image


That's it!!  Once you send those over I will merge for the 3.5 release

**Comment by Tropicalista** [comment]
The upload bar is working fine on my end. Are you sure that there is no extensions blocks upload?

Which browser are you using?

**Comment by gpickin** [comment]
FYI - Looks like you didn't rebase your changes. This has reversed a lot of updates in 3.1.
I will manually reverse all of them.

**Comment by gpickin** [comment]
Looking at the comments, @lmajano there was more than the date lost on the footer. All the clickable links are gone too.
I think I fixed all the regressions regarding i18n, and some other changes. 
Of course, @Tropicalista made a lot of good changes, so some of the changes were moot.
I'm going back through previous pulls looking at the footer now... I'll try and compare with the 3.1 release notes.

**Comment by Tropicalista** [comment]
@gpickin the new filebrowser has also his own repository [here](https://github.com/contentbox-modules/cbFilebrowser)

Can you try to use it? I've only added few i18n properties.

**Comment by gpickin** [comment]
You added some, but because the files you pushed weren't rebased against the changes we had made in 3.1, it removed several of the i18n settings.
I have updated all of those, by looking at your pull request.

**Pull request merged**
