### PR TITLE
Fix menu preview

### PR DESCRIPTION
**Pull request by Tropicalista**

### CODE REVIEW

**Comment by lmajano** [comment]
I am not sure why this would work, since the right mapping is `contentbox` not `cbapp`

**Comment by Tropicalista** [comment]
I'm on commandbox on Windows.

On a fresh install when I create a menu I got this error:

Oopsy! Something went wrong! Event: contentbox-admin:menus.preview Routed URL: cbadmin/menus/preview/ Layout: N/A (Module: ) View: N/A Timestamp: 10/24/2015 12:24:36 AM Type: expression Messages: invalid call of the function buildProviderMenu (E:\ColdfusionBuilder\ContentBox\modules\contentbox\models\system\CBHelper.cfc), first Argument (menu) is of invalid type, can't cast Object type [Component cbapp.modules.contentbox.models.menu.Menu] to a value of type [contentbox.models.menu.menu] Tag Context: Template: E:\ColdfusionBuilder\ContentBox\modules\contentbox-admin\handlers\menus.cfc LINE: 199: Menu.populateMenuItems( rawData=deserializeJSON( rc.menuItems ) ); 200: // render data 201: event.renderData( data=cb.buildProviderMenu( menu=Menu ), type="text" ); 202: } 203: Template: E:\ColdfusionBuilder\ContentBox\coldbox\system\EventHandler.cfc LINE: 76: any function _privateInvoker( required method, required argCollection ){ 77: var _targetAction = variables[ arguments.method ]; 78: var _targetResults = _targetAction( argumentCollection=argCollection ); 79: if( !isNull( _targetResults ) ){ return _targetResults; } 80: }

**Comment by Tropicalista** [comment]
If I try to dump Menu metadata:

image

You will see the component is cbapp.modules.contentbox.models.menu.Menu

**Comment by lmajano** [comment]
Yes it gives you the full path. This is strange as it should respect the per app mapping. Maybe I will have to duck type it.

**Comment by lmajano** [comment]
merged manually

**Pull request closed without merging**
