### PR TITLE
Fix CONTENTBOX-492

### PR DESCRIPTION
**Pull request by Tropicalista**
Better responsiveness to admin bar

### CODE REVIEW

**Comment by lmajano** [comment]
First of all, this looks great.
Few comments.
- When reducing width I see the text come in for indicators like "Home" "Add Content", etc.  I am not sure if those make sense to have, as the tooltips denote it and just creates textual noise.  

- When I reduce the width, I get two bars on each side of the logo, is that meant to be? Both do the same?

- The profile menu is hard coded instead of generated, any reason?

**Comment by Tropicalista** [comment]
1) when reduing you want to have only icons? 
2) there are two bars, one for the dropdown menu, the other for the sidebar menu
3) profile menu is hardcoded because I hace inserted avatar and removed the username to make more consistent with the other dropdown.

**Comment by Tropicalista** [comment]
This is the final look: http://embed.plnkr.co/MGsAQy/preview

If you want any modification, could you please give me some specifications?

**Comment by lmajano** [comment]
1) when reduing you want to have only icons?
Yes, no text underneath them
2) there are two bars, one for the dropdown menu, the other for the sidebar menu
Got it!
3) profile menu is hardcoded because I hace inserted avatar and removed the username to make more consistent with the other dropdown. 
Ok, can this be added dynamically back?

**Comment by lmajano** [comment]
Haven't forgotten about this one, but maybe we can re-evaluate it as we have done so many updates now.

**Comment by Tropicalista** [comment]
Sure Luis, I've stopped further development on this because once we have solved other bugs we can concentrate on this.

**Pull request closed without merging**
