### PR TITLE
Patch/CONTENTBOX-1307 default menu ordering

### PR DESCRIPTION
**Pull request by jclausen**
Commits:  

- Ignores vscode directory
- Resolves CONTENTBOX-1307 - Honors ordering customizations for page tree in navigation

### CODE REVIEW

**Comment by lmajano** [comment]
This looks good to me except the vscode settings. These are for the project only and don't reference anything on my machine.

**Comment by jclausen** [comment]
Correct.  That’s why I removed them from version control and ignored them.  That directory had been added to the repo.
________________________________

**Comment by lmajano** [comment]
You can't remove them is what I am saying LOL.  They are there to provide insights into the proejct if you use vscode. We can't ignore it or remove it.

**Comment by jclausen** [comment]
Oh, are you saying you want to keep that directory?  I just find it annoying under version control because it’s always showing as untracked changes.
________________________________

**Comment by jclausen** [comment]
[sigh] OK.  I’ll add it back…. [pouts]
________________________________

**Comment by jclausen** [comment]
Restored!

**Pull request merged**
