### PR TITLE
Feature/CONTENTBOX-1270 - ContentTemplates

### PR DESCRIPTION
**Pull request by jclausen**
Please merge PR #531, PR #536, and PR #537 before reviewing as their code is in this pull request.

This feature implements the ability to create and apply Content Templates to all Content Types.

I will DM a demonstration video in Slack as it is too big to upload here.

Also resolves CONTENTBOX-1448

### CODE REVIEW

**Comment by lmajano** [comment]
@jclausen this has now some simple conflicts to resolve.  Please let me know when it's ready for review as well.

**Comment by jclausen** [comment]
@lmajano Conflicts resolve and some cleanup commits pushed.  This one is ready for review.

**Comment by jclausen** [comment]
@lmajano [ bump ] for review

**Comment by lmajano** [comment]
Oops. On it

**Comment by jclausen** [comment]
[bumpity bump] :)

**Pull request merged**
